services:
  redis-chat-test:
    image: redis:alpine
    container_name: redis-chat-test
    ports:
      - "6379:6379"
    networks:
      - chat-network-test
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  mongo-chat-test:
    image: mongo:latest
    container_name: mongo-chat-test
    ports:
      - "27017:27017"
    networks:
      - chat-network-test
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  
  chat-test:
    build: .
    container_name: chat-test
    env_file:
      - ./test.env
    ports:
      - "50051:50051"
    depends_on:
      redis-chat-test:
        condition: service_healthy
      mongo-chat-test:
        condition: service_healthy
    networks:
      - chat-network-test
  
networks:
  chat-network-test:
    driver: bridge